#!/bin/sh
echo "JARVIS"
echo "What Would you like to Google sir?"
   
read F1
F=`echo $F1 | sed s/\ /+/g`
 
echo "Right away sir... | Google $F |"
sleep 2
open "http://google.com/search?q=$F"
echo "I Must Be Going Now Sir..."
echo "- JARVIS"
