#!/bin/bash

echo "Ping Device..."
sleep 2
echo "Author: Gavin Burris"
sleep 2
echo "Starting Now..."
END=255255255255
for ((i= 1000; i<=END; i++)); do
  echo $i | sed 's/\(.\)/\0./g' >> output.txt
  echo "Gathering all Ip's from the range 1.0.0.0 - 255.255.255.255"
  echo "Might take some time..."
done
cat output.txt |  while read output
do
  timeout 3s ping -c 1 "$output"
done
