#!/bin/sh
echo "JARVIS MESSAGING SYSTEMS"
sleep 1
echo "What number would you like to text sir?"
 
read F1
F=$F1           
echo "What would you like to send sir?"
 
read G1
G=$G1
content="curl http://textbelt.com/text -d number=$F1  -d "message=$G1""
echo "Sending |\" $G1 \" | to the number | \" $F1 \" |"
eval $content
echo "I Must Be Going Now Sir..."
echo "- JARVIS
                           
